# make it explicit that we favor the new container-based travis workers
sudo: false

language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"         # 3.5 development branch
  - "nightly"         # currently points to 3.6-dev

addons:
  apt:
    packages:
      - libatlas3gf-base
      - libatlas-dev
      # - libblas-dev
      - python-scipy
      # - python-numpy

# skip the install step
install: true

# command to run tests
script: nosetests
