# make it explicit that we favor the new container-based travis workers
sudo: false

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

# Install miniconda
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy nose
  # - conda install --yes -c dan_blanchard python-coveralls nose-cov
  # - python setup.py install
  - pip install coveralls

script:
  nosetests --with-coverage

after_success:
  coveralls

notifications:
  email: false
